-- MySQL Script generated by MySQL Workbench
-- Mon May 16 14:32:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Language` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `priceMultiplier` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_country` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_City_Countries1_idx` (`id_country` ASC) VISIBLE,
  CONSTRAINT `fk_City_Countries1`
    FOREIGN KEY (`id_country`)
    REFERENCES `mydb`.`Country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `id_city` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Addresses_City1_idx` (`id_city` ASC) VISIBLE,
  CONSTRAINT `fk_Addresses_City1`
    FOREIGN KEY (`id_city`)
    REFERENCES `mydb`.`City` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `pass` VARCHAR(32) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `id_language` INT NOT NULL,
  `id_address` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Languages1_idx` (`id_language` ASC) VISIBLE,
  INDEX `fk_User_Addresses1_idx` (`id_address` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_User_Languages1`
    FOREIGN KEY (`id_language`)
    REFERENCES `mydb`.`Language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Addresses1`
    FOREIGN KEY (`id_address`)
    REFERENCES `mydb`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Driver` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `rating` INT NOT NULL DEFAULT 50,
  `free` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Driver_User1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_Driver_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_address` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stores_Addresses1_idx` (`id_address` ASC) VISIBLE,
  CONSTRAINT `fk_Stores_Addresses1`
    FOREIGN KEY (`id_address`)
    REFERENCES `mydb`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Delivery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_store` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_driver` INT NOT NULL,
  `timeCreated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_CurrentDeliverys_Stores1_idx` (`id_store` ASC) VISIBLE,
  INDEX `fk_Delivery_User1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_Delivery_Driver1_idx` (`id_driver` ASC) VISIBLE,
  CONSTRAINT `fk_CurrentDeliverys_Stores1`
    FOREIGN KEY (`id_store`)
    REFERENCES `mydb`.`Store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Delivery_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Delivery_Driver1`
    FOREIGN KEY (`id_driver`)
    REFERENCES `mydb`.`Driver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PayInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PayInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `cardNumber` VARCHAR(16) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Payment_User1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_driver` INT NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `plate` VARCHAR(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vehicles_Driver1_idx` (`id_driver` ASC) VISIBLE,
  CONSTRAINT `fk_Vehicles_Driver1`
    FOREIGN KEY (`id_driver`)
    REFERENCES `mydb`.`Driver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`License`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`License` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_driver` INT NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_License_Driver1_idx` (`id_driver` ASC) VISIBLE,
  CONSTRAINT `fk_License_Driver1`
    FOREIGN KEY (`id_driver`)
    REFERENCES `mydb`.`Driver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_brand` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_Brands1_idx` (`id_brand` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Brands1`
    FOREIGN KEY (`id_brand`)
    REFERENCES `mydb`.`Brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `id_store` INT NOT NULL,
  `id_product` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id_store`, `id_product`),
  INDEX `fk_Stores_has_Products_Products1_idx` (`id_product` ASC) VISIBLE,
  INDEX `fk_Stores_has_Products_Stores1_idx` (`id_store` ASC) VISIBLE,
  CONSTRAINT `fk_Stores_has_Products_Stores1`
    FOREIGN KEY (`id_store`)
    REFERENCES `mydb`.`Store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stores_has_Products_Products1`
    FOREIGN KEY (`id_product`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeliveryProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DeliveryProduct` (
  `id_currentDelivery` INT NOT NULL,
  `id_product` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id_currentDelivery`, `id_product`),
  INDEX `fk_CurrentDeliverys_has_Products_Products1_idx` (`id_product` ASC) VISIBLE,
  INDEX `fk_CurrentDeliverys_has_Products_CurrentDeliverys1_idx` (`id_currentDelivery` ASC) VISIBLE,
  CONSTRAINT `fk_CurrentDeliverys_has_Products_CurrentDeliverys1`
    FOREIGN KEY (`id_currentDelivery`)
    REFERENCES `mydb`.`Delivery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CurrentDeliverys_has_Products_Products1`
    FOREIGN KEY (`id_product`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_store` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employee_Store1_idx` (`id_store` ASC) VISIBLE,
  INDEX `fk_Employee_User1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Store1`
    FOREIGN KEY (`id_store`)
    REFERENCES `mydb`.`Store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
